# Generated by Django 5.0.4 on 2024-05-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=9, verbose_name='Номер телефона')),
                ('question', models.TextField(verbose_name='Вопрос')),
            ],
        ),
    ]
