# Generated by Django 5.0.4 on 2024-05-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Ваш email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='question',
            field=models.TextField(verbose_name='Ваш вопрос'),
        ),
    ]
